// system_design/design-system/ui_kits/app/CommandPalette.jsx
/* global React, Icon, Kbd */
const { useState: useCState, useEffect: useCEffect } = React;

function CommandPalette({ open, onClose }) {
  const [query, setQuery] = useCState('');
  useCEffect(() => { if (open) setQuery(''); }, [open]);
  if (!open) return null;

  const cmds = [
    { icon: 'play',     label: 'Start nginx-prod',      scope: 'container', hot: ['⌘', '↵'] },
    { icon: 'square',   label: 'Stop nginx-prod',       scope: 'container' },
    { icon: 'rotate-ccw', label: 'Restart postgres-main', scope: 'container' },
    { icon: 'download', label: 'Pull nginx:1.27',       scope: 'image' },
    { icon: 'download', label: 'Pull postgres:16.3',    scope: 'image' },
    { icon: 'terminal', label: 'Open shell in worker-jobs', scope: 'container' },
    { icon: 'hammer',   label: 'Rebuild stack: production', scope: 'compose' },
    { icon: 'trash-2',  label: 'Prune unused images',   scope: 'system' },
  ].filter(c => c.label.toLowerCase().includes(query.toLowerCase()));

  return (
    <div className="palette-backdrop" onClick={onClose}>
      <div className="palette" onClick={e => e.stopPropagation()}>
        <div className="palette-search">
          <Icon name="search" size={16} />
          <input autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Type a command…" />
          <Kbd>esc</Kbd>
        </div>
        <div className="palette-list">
          {cmds.length === 0 && <div className="palette-empty">No commands match.</div>}
          {cmds.map((c, i) => (
            <div key={i} className={`palette-row ${i === 0 ? 'on' : ''}`}>
              <Icon name={c.icon} size={14} />
              <span className="palette-label" dangerouslySetInnerHTML={{ __html: highlight(c.label, query) }} />
              <span className="palette-scope mono">{c.scope}</span>
              {c.hot && <span className="palette-hot">{c.hot.map((k, j) => <Kbd key={j}>{k}</Kbd>)}</span>}
            </div>
          ))}
        </div>
        <div className="palette-foot">
          <span><Kbd>↑</Kbd><Kbd>↓</Kbd> navigate</span>
          <span><Kbd>↵</Kbd> run</span>
          <span><Kbd>⌘</Kbd><Kbd>↵</Kbd> run + close</span>
        </div>
      </div>
    </div>
  );
}

function highlight(label, q) {
  if (!q) return label;
  const i = label.toLowerCase().indexOf(q.toLowerCase());
  if (i < 0) return label;
  return label.slice(0, i) + `<mark>${label.slice(i, i + q.length)}</mark>` + label.slice(i + q.length);
}

Object.assign(window, { CommandPalette });

// frontend/src/app/components/shared/command-palette/command-palette.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { IconComponent } from '../icon/icon.component';
import { DockerService } from '../../../services/docker.service';
import { NotificationService } from '../../../services/notification.service';

interface PaletteCmd {
  icon: string;
  label: string;
  scope: string;
  action?: () => void;
  hot?: string[];
}

@Component({
  selector: 'app-command-palette',
  standalone: true,
  imports: [CommonModule, FormsModule, IconComponent],
  templateUrl: './command-palette.component.html',
})
export class CommandPaletteComponent implements OnChanges {
  @Input() open = false;
  @Output() closed = new EventEmitter<void>();

  query = '';
  selectedIdx = 0;
  filtered: PaletteCmd[] = [];

  private allCmds: PaletteCmd[] = [
    { icon: 'box',         label: 'Go to Containers',           scope: 'navigate',   action: () => this.router.navigate(['/containers']), hot: ['⌘', '1'] },
    { icon: 'layers',      label: 'Go to Images',               scope: 'navigate',   action: () => this.router.navigate(['/images']) },
    { icon: 'database',    label: 'Go to Volumes',              scope: 'navigate',   action: () => this.router.navigate(['/volumes']) },
    { icon: 'network',     label: 'Go to Networks',             scope: 'navigate',   action: () => this.router.navigate(['/networks']) },
    { icon: 'boxes',       label: 'Go to Stacks',               scope: 'navigate',   action: () => this.router.navigate(['/stacks']) },
    { icon: 'hammer',      label: 'Go to Builds',               scope: 'navigate',   action: () => this.router.navigate(['/builds']) },
    { icon: 'cloud',       label: 'Go to Registry',             scope: 'navigate',   action: () => this.router.navigate(['/registry']) },
    { icon: 'scroll-text', label: 'Go to Logs',                 scope: 'navigate',   action: () => this.router.navigate(['/logs']) },
    { icon: 'activity',    label: 'Go to Metrics',              scope: 'navigate',   action: () => this.router.navigate(['/metrics']) },
    { icon: 'rss',         label: 'Go to Events',               scope: 'navigate',   action: () => this.router.navigate(['/events']) },
    { icon: 'trash-2',     label: 'Prune stopped containers',   scope: 'system',     action: () => this.pruneContainers() },
    { icon: 'trash-2',     label: 'Prune unused images',        scope: 'system',     action: () => this.pruneImages() },
    { icon: 'trash-2',     label: 'Prune unused volumes',       scope: 'system',     action: () => this.pruneVolumes() },
    { icon: 'trash-2',     label: 'Prune unused networks',      scope: 'system',     action: () => this.pruneNetworks() },
    { icon: 'download',    label: 'Pull image…',                scope: 'image',      action: () => { this.close(); this.router.navigate(['/images']); } },
  ];

  constructor(
    private router: Router,
    private docker: DockerService,
    private notify: NotificationService,
  ) {}

  ngOnChanges(): void {
    if (this.open) {
      this.query = '';
      this.selectedIdx = 0;
      this.filtered = this.allCmds;
    }
  }

  onQuery(): void {
    const q = this.query.toLowerCase();
    this.filtered = q ? this.allCmds.filter(c => c.label.toLowerCase().includes(q)) : this.allCmds;
    this.selectedIdx = 0;
  }

  moveSelection(dir: number): void {
    this.selectedIdx = Math.max(0, Math.min(this.filtered.length - 1, this.selectedIdx + dir));
  }

  runSelected(): void {
    if (this.filtered[this.selectedIdx]) this.run(this.filtered[this.selectedIdx]);
  }

  run(cmd: PaletteCmd): void {
    this.close();
    cmd.action?.();
  }

  close(): void {
    this.closed.emit();
  }

  highlight(label: string): string {
    if (!this.query) return label;
    const i = label.toLowerCase().indexOf(this.query.toLowerCase());
    if (i < 0) return label;
    return label.slice(0, i) + `<mark>${label.slice(i, i + this.query.length)}</mark>` + label.slice(i + this.query.length);
  }

  private pruneContainers(): void {
    this.docker.pruneContainers().subscribe({
      next: () => this.notify.success('Stopped containers pruned'),
      error: () => this.notify.error('Prune failed'),
    });
  }

  private pruneImages(): void {
    this.docker.pruneImages().subscribe({
      next: () => this.notify.success('Unused images pruned'),
      error: () => this.notify.error('Prune failed'),
    });
  }

  private pruneVolumes(): void {
    this.docker.pruneVolumes().subscribe({
      next: () => this.notify.success('Unused volumes pruned'),
      error: () => this.notify.error('Prune failed'),
    });
  }

  private pruneNetworks(): void {
    this.docker.pruneNetworks().subscribe({
      next: () => this.notify.success('Unused networks pruned'),
      error: () => this.notify.error('Prune failed'),
    });
  }
}

    @if (open) {
      <div class="palette-backdrop" (click)="close()">
        <div class="palette" (click)="$event.stopPropagation()">
          <div class="palette-search">
            <dy-icon name="search" [size]="16"></dy-icon>
            <input #searchInput [(ngModel)]="query" (ngModelChange)="onQuery()"
                   placeholder="Type a command…"
                   (keydown.escape)="close()"
                   (keydown.arrowdown)="moveSelection(1)"
                   (keydown.arrowup)="moveSelection(-1)"
                   (keydown.enter)="runSelected()">
            <kbd class="kbd-mini">esc</kbd>
          </div>
          <div class="palette-list">
            @if (filtered.length === 0) {
              <div class="palette-empty">No commands match.</div>
            }
            @for (cmd of filtered; track $index) {
              <div class="palette-row" [class.on]="$index === selectedIdx"
                   (mouseenter)="selectedIdx = $index"
                   (click)="run(cmd)">
                <dy-icon [name]="cmd.icon" [size]="14"></dy-icon>
                <span class="palette-label" [innerHTML]="highlight(cmd.label)"></span>
                <span class="palette-scope mono">{{ cmd.scope }}</span>
                @if (cmd.hot) {
                  <span class="palette-hot">
                    @for (k of cmd.hot; track k) {
                      <kbd class="kbd-mini">{{ k }}</kbd>
                    }
                  </span>
                }
              </div>
            }
          </div>
          <div class="palette-foot">
            <span><kbd class="kbd-mini">↑</kbd><kbd class="kbd-mini">↓</kbd> navigate</span>
            <span><kbd class="kbd-mini">↵</kbd> run</span>
            <span><kbd class="kbd-mini">esc</kbd> close</span>
          </div>
        </div>
      </div>
    }
