// system_design/uploads/Dockyard Design System (2)/ui_kits/app/Dashboard.jsx
/* global React, Icon, Dot, Badge, ProjDot, PROJECTS */
const { useState: useDashState, useEffect: useDashEffect } = React;

/* ---- mini chart helpers ---- */
function DashSpark({ series, color, h = 48, fill = true }) {
  const max = Math.max(...series), min = Math.min(...series);
  const w = 240;
  const pts = series.map((v, i) => `${(i * w) / (series.length - 1)},${h - ((v - min) / (max - min || 1)) * (h - 6) - 3}`).join(' ');
  return (
    <svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{ width: '100%', height: h, display: 'block' }}>
      {fill && <polygon points={`0,${h} ${pts} ${w},${h}`} fill={color} opacity="0.10" />}
      <polyline points={pts} fill="none" stroke={color} strokeWidth="1.5" vectorEffect="non-scaling-stroke" />
    </svg>
  );
}

function Ring({ pct, color, size = 88, label, value }) {
  const r = size / 2 - 7, c = 2 * Math.PI * r;
  return (
    <div className="ring" style={{ width: size, height: size }}>
      <svg width={size} height={size}>
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke="var(--bg-inset)" strokeWidth="6" />
        <circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth="6" strokeLinecap="round"
          strokeDasharray={c} strokeDashoffset={c * (1 - pct / 100)}
          transform={`rotate(-90 ${size/2} ${size/2})`} style={{ transition: 'stroke-dashoffset 600ms var(--ease-out)' }} />
      </svg>
      <div className="ring-center">
        <div className="ring-value mono">{value}</div>
        <div className="ring-label">{label}</div>
      </div>
    </div>
  );
}

const ACTIVITY = [
  { t: '14:32:24', icon: 'play',       tone: 'running', text: 'nginx-prod started',                who: 'mara' },
  { t: '14:32:18', icon: 'circle-x',   tone: 'danger',  text: 'worker-jobs exited (137 OOM)',       who: 'engine' },
  { t: '14:31:55', icon: 'download',   tone: 'info',    text: 'pulled internal/api:2026.05',        who: 'ci' },
  { t: '14:28:08', icon: 'hammer',     tone: 'running', text: 'built web-storefront in 42s',         who: 'mara' },
  { t: '14:24:14', icon: 'git-commit-horizontal', tone: 'info', text: 'pushed 2 commits to jobs-api', who: 'mara' },
  { t: '14:20:01', icon: 'rocket',     tone: 'running', text: 'deployed analytics-worker',           who: 'kai' },
];

function Dashboard() {
  const [now, setNow] = useDashState(new Date());
  useDashEffect(() => { const iv = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(iv); }, []);
  const time = now.toLocaleTimeString('en-US', { hour12: false });
  const date = now.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' });

  const running = PROJECTS.filter(p => p.status === 'running').length;
  const building = PROJECTS.filter(p => p.status === 'building').length;
  const failed = PROJECTS.filter(p => p.status === 'failed').length;

  return (
    <div className="dash">
      {/* header band */}
      <div className="dash-header">
        <div className="dash-header-left">
          <div className="dash-env">
            <Dot tone="running" size={9} />
            <span className="dash-env-name">production</span>
            <span className="dash-env-region mono">us-east-1 · 14 nodes</span>
          </div>
          <h1 className="dash-h1">All systems operational</h1>
        </div>
        <div className="dash-clock">
          <div className="dash-time mono">{time}</div>
          <div className="dash-date">{date}</div>
        </div>
      </div>

      {/* hero KPI row */}
      <div className="dash-kpis">
        <KpiCard icon="box" label="Containers" value="12" sub="of 14 running" tone="running" series={[8,9,9,10,11,10,12,11,12,12]} />
        <KpiCard icon="rocket" label="Projects" value={String(running)} sub={`${building} building · ${failed} failed`} tone="info" series={[3,3,4,4,5,5,5,6,6,6]} />
        <KpiCard icon="layers" label="Images" value="38" sub="1.6 GB · 198 MB reclaimable" tone="info" series={[30,31,33,34,35,36,37,37,38,38]} />
        <KpiCard icon="git-commit-horizontal" label="Deploys today" value="24" sub="avg 47s · 96% success" tone="running" series={[2,5,8,11,14,17,19,21,23,24]} />
      </div>

      <div className="dash-grid">
        {/* resource gauges */}
        <div className="dash-card span-4">
          <div className="dash-card-head"><span className="eyebrow">Host resources</span><span className="mono dim">live · 5s</span></div>
          <div className="rings">
            <Ring pct={12} color="#22D3EE" value="12%" label="CPU" />
            <Ring pct={52} color="#34D399" value="8.4G" label="Memory" />
            <Ring pct={89} color="#FBBF24" value="89%" label="Disk" />
          </div>
          <div className="res-foot mono">
            <span>16 cores</span><span>16 GB RAM</span><span>244 GB SSD</span>
          </div>
        </div>

        {/* throughput chart */}
        <div className="dash-card span-8">
          <div className="dash-card-head">
            <span className="eyebrow">Cluster throughput · last 60m</span>
            <div className="legend">
              <span className="leg-it"><span className="leg-dot" style={{ background: '#22D3EE' }} /> requests/s</span>
              <span className="leg-it"><span className="leg-dot" style={{ background: '#34D399' }} /> network in</span>
            </div>
          </div>
          <div className="dual-chart">
            <DashSpark series={[42,48,45,60,72,68,90,84,76,98,92,110,104,96,120,112,124]} color="#22D3EE" h={120} />
          </div>
          <div className="chart-axis mono"><span>13:32</span><span>13:47</span><span>14:02</span><span>14:17</span><span>14:32</span></div>
        </div>

        {/* projects status */}
        <div className="dash-card span-7">
          <div className="dash-card-head"><span className="eyebrow">Projects</span><span className="mono dim">{running} running · {PROJECTS.length} total</span></div>
          <div className="dash-proj-grid">
            {PROJECTS.map(p => (
              <div key={p.id} className={`dash-proj dash-proj-${p.status}`}>
                <div className="dash-proj-top">
                  <ProjDot status={p.status} size={9} />
                  <span className="dash-proj-name">{p.name}</span>
                  <Icon name={p.type === 'Compose' ? 'boxes' : 'file-code'} size={12} color="var(--fg-subtle)" />
                </div>
                <div className="dash-proj-meta mono">
                  {p.status === 'running' ? <span>{p.cpu} · {p.mem}</span>
                    : p.status === 'building' ? <span className="amber">building {p.buildProgress}%</span>
                    : p.status === 'failed' ? <span className="red">build failed</span>
                    : <span>{p.lastDeploy}</span>}
                  {p.ports[0] && <span className="dash-proj-port mono">:{p.ports[0].host}</span>}
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* activity feed */}
        <div className="dash-card span-5">
          <div className="dash-card-head"><span className="eyebrow">Live activity</span><span className="mono live-pulse"><Dot tone="running" size={6} /> live</span></div>
          <div className="dash-activity">
            {ACTIVITY.map((a, i) => (
              <div className="dash-act-row" key={i}>
                <span className="dash-act-time mono">{a.t}</span>
                <span className={`dash-act-ic dash-act-${a.tone}`}><Icon name={a.icon} size={11} /></span>
                <span className="dash-act-text">{a.text}</span>
                <span className="dash-act-who mono">{a.who}</span>
              </div>
            ))}
          </div>
        </div>

        {/* node strip */}
        <div className="dash-card span-12">
          <div className="dash-card-head"><span className="eyebrow">Nodes · us-east-1</span><span className="mono dim">14 healthy · 0 draining</span></div>
          <div className="node-strip">
            {Array.from({ length: 14 }).map((_, i) => {
              const load = [12,34,8,56,22,44,18,72,30,15,48,26,9,38][i];
              const tone = load > 70 ? 'warn' : 'running';
              return (
                <div className="node-cell" key={i} title={`node-${i+1} · ${load}%`}>
                  <div className="node-bar"><div className={`node-fill node-${tone}`} style={{ height: `${load}%` }} /></div>
                  <span className="node-id mono">{String(i+1).padStart(2,'0')}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

function KpiCard({ icon, label, value, sub, tone, series }) {
  const color = { running: '#34D399', info: '#22D3EE', warn: '#FBBF24', danger: '#F87171' }[tone] || '#22D3EE';
  return (
    <div className="kpi-card">
      <div className="kpi-top">
        <span className="kpi-ic" style={{ color }}><Icon name={icon} size={16} /></span>
        <span className="kpi-label">{label}</span>
      </div>
      <div className="kpi-value mono">{value}</div>
      <div className="kpi-sub">{sub}</div>
      <div className="kpi-spark"><DashSpark series={series} color={color} h={36} /></div>
    </div>
  );
}

Object.assign(window, { Dashboard });

// frontend/src/app/components/dashboard/dashboard.component.ts
﻿import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { forkJoin } from 'rxjs';
import { DockerService } from '../../services/docker.service';
import {
  SystemInfo, HostStats, DiskUsage, AppEvent, Project, ProjectStatus,
} from '../../models/docker.models';
import { IconComponent } from '../shared/icon/icon.component';
import { StatusDotComponent } from '../shared/status-dot/status-dot.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, IconComponent, StatusDotComponent],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
})
export class DashboardComponent implements OnInit, OnDestroy {
  loading = true;
  info: SystemInfo | null = null;
  projects: Project[] = [];
  events: AppEvent[] = [];
  diskUsage: DiskUsage | null = null;
  hostStats: HostStats | null = null;

  now = new Date();
  private clockTimer?: ReturnType<typeof setInterval>;
  private statsTimer?: ReturnType<typeof setInterval>;

  // Live host-load history, accumulated from the real 5s host-stats poll.
  cpuHistory: number[] = [];
  memHistory: number[] = [];

  // Ring gauge constants
  readonly ringR = 37;
  readonly ringC = +(2 * Math.PI * 37).toFixed(3);

  constructor(private docker: DockerService) {}

  ngOnInit(): void {
    this.clockTimer = setInterval(() => { this.now = new Date(); }, 1000);
    this.load();
    this.loadMetricHistory();
    this.statsTimer = setInterval(() => { this.loadHostStats(); }, 5000);
  }

  ngOnDestroy(): void {
    if (this.clockTimer) clearInterval(this.clockTimer);
    if (this.statsTimer) clearInterval(this.statsTimer);
  }

  load(): void {
    this.loading = true;
    forkJoin({
      info: this.docker.getSystemInfo(),
      projects: this.docker.listProjects(),
      events: this.docker.getEvents(),
      diskUsage: this.docker.getDiskUsage(),
    }).subscribe({
      next: ({ info, projects, events, diskUsage }) => {
        this.info = info;
        this.projects = projects ?? [];
        this.events = events ?? [];
        this.diskUsage = diskUsage;
        this.loading = false;
        this.loadHostStats();
      },
      error: () => { this.loading = false; },
    });
  }

  private loadHostStats(): void {
    this.docker.getHostStats().subscribe({
      next: stats => {
        this.hostStats = stats;
        // Append the live reading to the persisted history (last ~hour).
        this.cpuHistory = [...this.cpuHistory, this.cpuPct].slice(-240);
        this.memHistory = [...this.memHistory, this.memPct].slice(-240);
      },
      error: () => { /* rings stay at 0 if endpoint unavailable */ },
    });
  }

  // Seed the host-load chart from the persisted time-series so it shows real
  // history immediately instead of building up from empty.
  private loadMetricHistory(): void {
    this.docker.getMetricsHistory(3600).subscribe({
      next: samples => {
        if (samples?.length) {
          this.cpuHistory = samples.map(s => Math.round(s.cpu_pct));
          this.memHistory = samples.map(s => s.mem_total ? Math.round(s.mem_used / s.mem_total * 100) : 0);
        }
      },
      error: () => { /* no history yet */ },
    });
  }

  // Computed properties

  get time(): string {
    return this.now.toLocaleTimeString('en-GB', { hour12: false });
  }

  get date(): string {
    return this.now.toLocaleDateString('en-US', { weekday: 'long', month: 'short', day: 'numeric' });
  }

  get headline(): string {
    const failed = this.projects.filter(p => p.status === 'failed').length;
    if (failed > 0) return 'Some builds require attention';
    return 'All systems operational';
  }

  get projectsRunning(): number {
    return this.projects.filter(p => p.status === 'running').length;
  }

  get projectsBuilding(): number {
    return this.projects.filter(p => p.status === 'building').length;
  }

  get projectsFailed(): number {
    return this.projects.filter(p => p.status === 'failed').length;
  }

  get dashProjects(): Project[] {
    return this.projects.slice(0, 6);
  }

  get deploysToday(): number {
    const today = new Date().toDateString();
    return this.events.filter(e =>
      new Date(e.created_at).toDateString() === today &&
      (e.kind.includes('success') || e.kind.includes('deploy') || e.kind.includes('build'))
    ).length;
  }

  get successRate(): number {
    const today = new Date().toDateString();
    const todayEvents = this.events.filter(e => new Date(e.created_at).toDateString() === today);
    if (todayEvents.length === 0) return 100;
    const failed = todayEvents.filter(e => e.kind.includes('fail')).length;
    return Math.round((todayEvents.length - failed) / todayEvents.length * 100);
  }

  get totalImageSize(): number {
    return this.diskUsage?.Images?.reduce((s: number, img: any) => s + (img.Size ?? 0), 0) ?? 0;
  }

  get cpuPct(): number {
    return this.hostStats ? Math.round(this.hostStats.cpu_pct) : 0;
  }

  get memPct(): number {
    if (!this.hostStats?.mem_total) return 0;
    return Math.round(this.hostStats.mem_used / this.hostStats.mem_total * 100);
  }

  get memUsedGB(): string {
    if (!this.hostStats?.mem_used) return '—';
    const gb = this.hostStats.mem_used / (1024 ** 3);
    return gb >= 1 ? gb.toFixed(1) : `${(this.hostStats.mem_used / (1024 ** 2)).toFixed(0)}M`;
  }

  get diskPct(): number {
    if (!this.hostStats?.disk_total) return 0;
    return Math.round(this.hostStats.disk_used / this.hostStats.disk_total * 100);
  }

  get activityEvents(): AppEvent[] {
    const skip = new Set(['connect', 'disconnect', 'mount', 'unmount', 'create']);
    return this.events.filter(e => {
      if (e.object_type === 'network' || e.object_type === 'volume') return false;
      if (e.object_type === 'container' && skip.has(e.kind)) return false;
      // Skip low-signal image churn (untagged/deleted images by digest)
      if (e.object_type === 'image' && (e.object_name || '').startsWith('sha256:')) return false;
      return true;
    }).slice(0, 10);
  }

  // Ring helpers

  ringOffset(pct: number): number {
    return this.ringC * (1 - Math.min(100, Math.max(0, pct)) / 100);
  }

  // Sparkline helpers

  sparkPoints(series: number[], h = 36, w = 240): string {
    if (!series?.length) return '';
    const max = Math.max(...series);
    const min = Math.min(...series);
    const range = max - min || 1;
    return series.map((v, i) => {
      const x = series.length > 1 ? (i * w) / (series.length - 1) : w / 2;
      const y = h - ((v - min) / range) * (h - 6) - 3;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    }).join(' ');
  }

  sparkPoly(series: number[], h = 36, w = 240): string {
    if (!series?.length) return '';
    return `0,${h} ${this.sparkPoints(series, h, w)} ${w},${h}`;
  }

  // Fixed 0–100% scale chart, used for the live host CPU/memory history.
  pctPoints(series: number[], h = 120, w = 480): string {
    if (!series?.length) return '';
    return series.map((v, i) => {
      const x = series.length > 1 ? (i * w) / (series.length - 1) : w / 2;
      const y = h - (Math.min(100, Math.max(0, v)) / 100) * (h - 6) - 3;
      return `${x.toFixed(1)},${y.toFixed(1)}`;
    }).join(' ');
  }

  pctPoly(series: number[], h = 120, w = 480): string {
    if (!series?.length) return '';
    return `0,${h} ${this.pctPoints(series, h, w)} ${w},${h}`;
  }

  // Project helpers

  projCardClass(status: ProjectStatus): string {
    const map: Partial<Record<ProjectStatus, string>> = {
      running:  'dash-proj-running',
      building: 'dash-proj-building',
      failed:   'dash-proj-failed',
    };
    return map[status] ?? '';
  }

  projTone(status: ProjectStatus): 'running' | 'warn' | 'danger' | 'idle' | 'info' | 'accent' {
    if (status === 'running')  return 'running';
    if (status === 'building') return 'warn';
    if (status === 'failed')   return 'danger';
    return 'idle';
  }

  projPort(project: Project): string {
    if (!project.ports) return '';
    const first = project.ports.split(',')[0]?.trim();
    return first?.split(':')[0] ?? '';
  }

  // Activity helpers

  actLabel(e: AppEvent): string {
    const raw = e.object_name || e.image || '';
    // Shorten sha256 digests to something readable
    const name = raw.startsWith('sha256:')
      ? (e.image || 'image:' + raw.slice(7, 15))
      : (raw.split('/').pop() || raw);
    switch (e.kind) {
      case 'start':   return `${name} started`;
      case 'stop':    return `${name} stopped`;
      case 'die':     return `${name} exited`;
      case 'kill':    return `${name} killed`;
      case 'destroy': return `${name} removed`;
      case 'rename':  return `${name} renamed`;
      case 'pause':   return `${name} paused`;
      case 'unpause': return `${name} resumed`;
      case 'restart': return `${name} restarted`;
      case 'pull':    return `pulled ${name}`;
      case 'push':    return `pushed ${name}`;
      case 'untag':
      case 'delete':  return `deleted ${name}`;
      case 'project_start':          return `${name} started`;
      case 'project_stop':           return `${name} stopped`;
      case 'project_build_success':  return `${name} built`;
      case 'project_build_failed':   return `${name} build failed`;
      case 'project_deploy':         return `${name} deployed`;
      case 'update_available':       return `update available · ${name}`;
      case 'auto_update':            return `${name} auto-updated`;
      default: return name ? `${name} · ${e.kind}` : e.kind;
    }
  }

  actIcon(kind: string): string {
    if (kind.includes('success') || kind.includes('start') || kind === 'deploy') return 'check';
    if (kind.includes('fail') || kind.includes('die'))   return 'circle-x';
    if (kind.includes('available') || kind.includes('update')) return 'arrow-down-circle';
    if (kind.includes('build'))  return 'hammer';
    if (kind.includes('stop'))   return 'square';
    return 'activity';
  }

  actTone(kind: string): string {
    if (kind.includes('success') || kind.includes('start') || kind === 'deploy') return 'running';
    if (kind.includes('fail') || kind.includes('die'))   return 'danger';
    if (kind.includes('available') || kind.includes('update')) return 'info';
    if (kind.includes('warn')) return 'warn';
    return 'idle';
  }

  formatActTime(ts: string): string {
    if (!ts) return '—';
    return new Date(ts).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', hour12: false });
  }

  timeAgo(ts: string): string {
    if (!ts) return 'never';
    const d = new Date(ts);
    if (isNaN(d.getTime()) || d.getFullYear() < 2000) return 'never';
    const secs = Math.floor((Date.now() - d.getTime()) / 1000);
    if (secs < 5)     return 'just now';
    if (secs < 60)    return `${secs}s ago`;
    if (secs < 3600)  return `${Math.floor(secs / 60)}m ago`;
    if (secs < 86400) return `${Math.floor(secs / 3600)}h ago`;
    return `${Math.floor(secs / 86400)}d ago`;
  }

  formatGB(bytes?: number): string {
    if (!bytes) return '—';
    const gb = bytes / (1024 ** 3);
    return gb >= 1 ? `${gb.toFixed(1)} GB` : `${(bytes / (1024 ** 2)).toFixed(0)} MB`;
  }
}

<div class="dash">

  <!-- ── Header band ──────────────────────────────────────────────────── -->
  <div class="dash-header">
    <div class="dash-header-left">
      <div class="dash-env">
        <dy-dot tone="running" [size]="9"></dy-dot>
        <span class="dash-env-name mono">{{ info?.Name || 'local' }}</span>
        <span class="dash-env-region">{{ info?.OperatingSystem }} · {{ info?.NCPU }} cores</span>
      </div>
      <h1 class="dash-h1">{{ headline }}</h1>
    </div>
    <div class="dash-clock">
      <div class="dash-time mono">{{ time }}</div>
      <div class="dash-date">{{ date }}</div>
    </div>
  </div>

  @if (loading) {
    <div class="dash-loading">connecting…</div>
  } @else {

    <!-- ── KPI row ──────────────────────────────────────────────────────── -->
    <div class="dash-kpis">

      <!-- CONTAINERS -->
      <div class="kpi-card">
        <div class="kpi-top">
          <span class="kpi-ic" style="color:var(--running-400)">
            <dy-icon name="box" [size]="16"></dy-icon>
          </span>
          <span class="kpi-label">Containers</span>
        </div>
        <div class="kpi-value mono">{{ info?.ContainersRunning ?? 0 }}</div>
        <div class="kpi-sub">of {{ info?.Containers ?? 0 }} total</div>
      </div>

      <!-- PROJECTS -->
      <div class="kpi-card">
        <div class="kpi-top">
          <span class="kpi-ic" style="color:var(--accent)">
            <dy-icon name="rocket" [size]="16"></dy-icon>
          </span>
          <span class="kpi-label">Projects</span>
        </div>
        <div class="kpi-value mono">{{ projects.length }}</div>
        <div class="kpi-sub">{{ projectsBuilding }} building · {{ projectsFailed }} failed</div>
      </div>

      <!-- IMAGES -->
      <div class="kpi-card">
        <div class="kpi-top">
          <span class="kpi-ic" style="color:var(--info-400)">
            <dy-icon name="layers" [size]="16"></dy-icon>
          </span>
          <span class="kpi-label">Images</span>
        </div>
        <div class="kpi-value mono">{{ info?.Images ?? 0 }}</div>
        <div class="kpi-sub">{{ formatGB(totalImageSize) }} total</div>
      </div>

      <!-- EVENTS TODAY -->
      <div class="kpi-card">
        <div class="kpi-top">
          <span class="kpi-ic" style="color:var(--running-400)">
            <dy-icon name="git-commit-horizontal" [size]="16"></dy-icon>
          </span>
          <span class="kpi-label">Events today</span>
        </div>
        <div class="kpi-value mono">{{ deploysToday }}</div>
        <div class="kpi-sub">{{ successRate }}% success rate</div>
      </div>

    </div>

    <!-- ── Main 12-col grid ─────────────────────────────────────────────── -->
    <div class="dash-grid">

      <!-- HOST RESOURCES — span-4 -->
      <div class="dash-card span-4">
        <div class="dash-card-head">
          <span class="eyebrow">Host resources</span>
          <span class="dim mono">live · 5s</span>
        </div>
        <div class="rings">

          <!-- CPU ring -->
          <div class="ring">
            <svg [attr.width]="88" [attr.height]="88">
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="var(--bg-inset)" stroke-width="6"/>
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="#22D3EE" stroke-width="6"
                stroke-linecap="round"
                [attr.stroke-dasharray]="ringC"
                [attr.stroke-dashoffset]="ringOffset(cpuPct)"
                transform="rotate(-90 44 44)"/>
            </svg>
            <div class="ring-center">
              <div class="ring-value mono">{{ cpuPct | number:'1.0-0' }}%</div>
              <div class="ring-label">CPU</div>
            </div>
          </div>

          <!-- Memory ring -->
          <div class="ring">
            <svg [attr.width]="88" [attr.height]="88">
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="var(--bg-inset)" stroke-width="6"/>
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="#34D399" stroke-width="6"
                stroke-linecap="round"
                [attr.stroke-dasharray]="ringC"
                [attr.stroke-dashoffset]="ringOffset(memPct)"
                transform="rotate(-90 44 44)"/>
            </svg>
            <div class="ring-center">
              <div class="ring-value mono">{{ memUsedGB }}G</div>
              <div class="ring-label">Memory</div>
            </div>
          </div>

          <!-- Disk ring -->
          <div class="ring">
            <svg [attr.width]="88" [attr.height]="88">
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="var(--bg-inset)" stroke-width="6"/>
              <circle cx="44" cy="44" [attr.r]="ringR" fill="none" stroke="#FBBF24" stroke-width="6"
                stroke-linecap="round"
                [attr.stroke-dasharray]="ringC"
                [attr.stroke-dashoffset]="ringOffset(diskPct)"
                transform="rotate(-90 44 44)"/>
            </svg>
            <div class="ring-center">
              <div class="ring-value mono">{{ diskPct | number:'1.0-0' }}%</div>
              <div class="ring-label">Disk</div>
            </div>
          </div>

        </div>
        <div class="res-foot mono">
          <span>{{ info?.NCPU }} cores</span>
          <span>{{ formatGB(info?.MemTotal) }} RAM</span>
          <span>{{ formatGB(hostStats?.disk_total) }} SSD</span>
        </div>
      </div>

      <!-- HOST LOAD (live) — span-8 -->
      <div class="dash-card span-8">
        <div class="dash-card-head">
          <span class="eyebrow">Host load · live</span>
          <div class="legend">
            <span class="leg-it"><span class="leg-dot" style="background:#22D3EE"></span>CPU %</span>
            <span class="leg-it"><span class="leg-dot" style="background:#34D399"></span>Memory %</span>
          </div>
        </div>
        <div class="dual-chart">
          @if (cpuHistory.length < 2) {
            <div class="dash-empty" style="height:120px;display:flex;align-items:center;justify-content:center;">Collecting live samples…</div>
          } @else {
            <svg viewBox="0 0 480 120" preserveAspectRatio="none" style="width:100%;height:120px;display:block">
              <polygon [attr.points]="pctPoly(cpuHistory)" fill="#22D3EE" opacity="0.07"/>
              <polyline [attr.points]="pctPoints(cpuHistory)" fill="none" stroke="#22D3EE" stroke-width="1.5" vector-effect="non-scaling-stroke"/>
              <polygon [attr.points]="pctPoly(memHistory)" fill="#34D399" opacity="0.07"/>
              <polyline [attr.points]="pctPoints(memHistory)" fill="none" stroke="#34D399" stroke-width="1.5" vector-effect="non-scaling-stroke"/>
            </svg>
          }
        </div>
      </div>

      <!-- PROJECTS — span-7 -->
      <div class="dash-card span-7">
        <div class="dash-card-head">
          <span class="eyebrow">Projects</span>
          <span class="dim mono">{{ projectsRunning }} running · {{ projects.length }} total</span>
        </div>
        @if (dashProjects.length === 0) {
          <div class="dash-empty">No projects configured</div>
        } @else {
          <div class="dash-proj-grid">
            @for (p of dashProjects; track p.id) {
              <div class="dash-proj" [ngClass]="projCardClass(p.status)">
                <div class="dash-proj-top">
                  <dy-dot [tone]="projTone(p.status)" [size]="9"></dy-dot>
                  <span class="dash-proj-name">{{ p.name }}</span>
                  <dy-icon [name]="p.type === 'compose' ? 'boxes' : 'file-code'" [size]="12" style="color:var(--fg-subtle);flex:none"></dy-icon>
                </div>
                <div class="dash-proj-meta mono">
                  @if (p.status === 'running') {
                    <span style="color:var(--running-400)">running</span>
                  } @else if (p.status === 'building') {
                    <span class="amber">building…</span>
                  } @else if (p.status === 'failed') {
                    <span class="red">failed</span>
                  } @else {
                    <span>{{ timeAgo(p.updated_at) }}</span>
                  }
                  @if (projPort(p)) {
                    <span class="dash-proj-port">:{{ projPort(p) }}</span>
                  }
                </div>
              </div>
            }
          </div>
        }
      </div>

      <!-- LIVE ACTIVITY — span-5 -->
      <div class="dash-card span-5">
        <div class="dash-card-head">
          <span class="eyebrow">Live activity</span>
          <span class="live-pulse">
            <dy-dot tone="running" [size]="6"></dy-dot>
            live
          </span>
        </div>
        <div class="dash-activity">
          @if (activityEvents.length === 0) {
            <div class="dash-empty">No recent activity</div>
          }
          @for (e of activityEvents; track e.id) {
            <div class="dash-act-row">
              <span class="dash-act-time mono">{{ formatActTime(e.created_at) }}</span>
              <span class="dash-act-ic" [ngClass]="'dash-act-' + actTone(e.kind)">
                <dy-icon [name]="actIcon(e.kind)" [size]="11"></dy-icon>
              </span>
              <span class="dash-act-text">{{ actLabel(e) }}</span>
              <span class="dash-act-who mono">{{ e.actor || '—' }}</span>
            </div>
          }
        </div>
      </div>

    </div>
  }

</div>
