// system_design/design-system/ui_kits/app/Roles.jsx
/* global React, Icon, Btn, Badge, ROLE_META, MEMBERS */
const { useState: useRState } = React;

/* Role list — the 6 system roles plus one example custom role.
   Member counts tie back to MEMBERS. */
const ROLES = [
  { id: 'owner',      icon: 'crown',       type: 'system', members: 1, envSummary: 'All environments', level: 'Full access' },
  { id: 'admin',      icon: 'shield',      type: 'system', members: 2, envSummary: 'All environments', level: 'Manage + deploy' },
  { id: 'maintainer', icon: 'wrench',      type: 'system', members: 2, envSummary: '3 environments',    level: 'Operate + deploy' },
  { id: 'developer',  icon: 'code',        type: 'system', members: 4, envSummary: 'staging, dev',       level: 'Build + operate' },
  { id: 'viewer',     icon: 'eye',         type: 'system', members: 2, envSummary: '3 · read-only',      level: 'Read-only' },
  { id: 'billing',    icon: 'credit-card', type: 'system', members: 1, envSummary: 'No access',          level: 'Billing only' },
  { id: 'sre',        icon: 'siren',       type: 'custom', members: 0, envSummary: 'production',          level: 'Operate (prod)',
    label: 'On-call SRE', desc: 'Operate and deploy production only. For rotation engineers handling incidents.' },
];

const ROLE_ENV = {
  owner:      [['production','deploy'],['staging','deploy'],['dev','deploy']],
  admin:      [['production','write'], ['staging','write'], ['dev','write']],
  maintainer: [['production','deploy'],['staging','read'],  ['dev','read']],
  developer:  [['production','none'],  ['staging','write'], ['dev','deploy']],
  viewer:     [['production','read'],  ['staging','read'],  ['dev','read']],
  billing:    [['production','none'],  ['staging','none'],  ['dev','none']],
  sre:        [['production','deploy'],['staging','none'],  ['dev','none']],
};
const PERM_TXT = { deploy: 'deploy', write: 'write', read: 'read', none: 'no access' };

/* Capability matrix. Each value is one of: all | scoped | read | none */
const CAP_GROUPS = [
  { group: 'Containers', rows: [
    { label: 'View containers & logs', vals: { owner:'all', admin:'all', maintainer:'all', developer:'all', viewer:'read', billing:'none', sre:'all' } },
    { label: 'Start, stop, restart',   vals: { owner:'all', admin:'all', maintainer:'all', developer:'scoped', viewer:'none', billing:'none', sre:'scoped' } },
    { label: 'Open shell / exec',      vals: { owner:'all', admin:'all', maintainer:'all', developer:'scoped', viewer:'none', billing:'none', sre:'scoped' } },
    { label: 'Remove containers',      vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'none', viewer:'none', billing:'none', sre:'scoped' } },
  ]},
  { group: 'Images & builds', rows: [
    { label: 'Pull images',     vals: { owner:'all', admin:'all', maintainer:'all', developer:'scoped', viewer:'read', billing:'none', sre:'scoped' } },
    { label: 'Build images',    vals: { owner:'all', admin:'all', maintainer:'all', developer:'scoped', viewer:'none', billing:'none', sre:'none' } },
    { label: 'Push to registry',vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'none', viewer:'none', billing:'none', sre:'none' } },
    { label: 'Prune images',    vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'none', viewer:'none', billing:'none', sre:'scoped' } },
  ]},
  { group: 'Infrastructure', rows: [
    { label: 'Volumes & networks', vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'scoped', viewer:'read', billing:'none', sre:'scoped' } },
    { label: 'Prune resources',    vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'none', viewer:'none', billing:'none', sre:'scoped' } },
  ]},
  { group: 'Deployments', rows: [
    { label: 'Deploy & rollback', vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'scoped', viewer:'none', billing:'none', sre:'scoped' } },
  ]},
  { group: 'Organization', rows: [
    { label: 'Invite & remove members', vals: { owner:'all', admin:'all', maintainer:'none', developer:'none', viewer:'none', billing:'none', sre:'none' } },
    { label: 'Manage roles',            vals: { owner:'all', admin:'all', maintainer:'none', developer:'none', viewer:'none', billing:'none', sre:'none' } },
    { label: 'Manage billing',          vals: { owner:'all', admin:'none', maintainer:'none', developer:'none', viewer:'none', billing:'all', sre:'none' } },
    { label: 'API tokens & registries', vals: { owner:'all', admin:'all', maintainer:'scoped', developer:'none', viewer:'none', billing:'none', sre:'scoped' } },
  ]},
];

const CAP_STATE = {
  all:    { cls: 'all',    icon: 'check',  label: 'all envs' },
  scoped: { cls: 'scoped', icon: 'check',  label: 'assigned' },
  read:   { cls: 'read',   icon: null,     label: 'read-only' },
  none:   { cls: 'none',   icon: null,     label: '—' },
};

function roleName(r) { return r.label || ROLE_META[r.id]?.label || r.id; }
function roleDesc(r) { return r.desc || ROLE_META[r.id]?.desc || ''; }

/* =========================================================================
   ROLES — list
   ========================================================================= */
function RolesPage({ rows, selectedId, setSelectedId, filter, setFilter, onNewRole }) {
  const filtered = rows.filter(r => filter === 'all' || r.type === filter);
  const cols = 'minmax(0,1.7fr) 84px minmax(0,1.25fr) 132px 30px';
  const counts = {
    all: rows.length,
    system: rows.filter(r => r.type === 'system').length,
    custom: rows.filter(r => r.type === 'custom').length,
  };

  return (
    <div className="content-area">
      <div className="content-head">
        <div className="content-title-row">
          <h2 className="content-title">Roles</h2>
          <span className="content-count mono">{filtered.length} of {rows.length}</span>
        </div>
        <div className="content-actions">
          <Btn variant="ghost" icon="git-compare">Compare</Btn>
          <span className="divider-v" />
          <Btn variant="primary" icon="plus" onClick={onNewRole}>New role</Btn>
        </div>
      </div>

      <div className="content-toolbar">
        <div className="pills">
          {[
            { id: 'all',    label: 'All' },
            { id: 'system', label: 'System' },
            { id: 'custom', label: 'Custom' },
          ].map(f => (
            <button key={f.id} className={`pill ${filter === f.id ? 'on' : ''}`} onClick={() => setFilter(f.id)}>
              {f.label}<span className="pill-count">{counts[f.id]}</span>
            </button>
          ))}
        </div>
        <div className="toolbar-meta mono">{counts.system} system · {counts.custom} custom</div>
      </div>

      <div className="gtable roles-table">
        <div className="gtable-head" style={{ gridTemplateColumns: cols }}>
          <span>Role</span>
          <span>Members</span>
          <span>Environment access</span>
          <span>Access level</span>
          <span></span>
        </div>
        {filtered.map(r => (
          <div
            key={r.id}
            className={`gtable-row roles-row ${selectedId === r.id ? 'sel' : ''}`}
            style={{ gridTemplateColumns: cols }}
            onClick={() => setSelectedId(r.id)}
          >
            <span className="role-list-name">
              <span className={`role-ic ${r.id === 'owner' ? 'owner' : ''} ${r.type === 'custom' ? 'custom' : ''}`}>
                <Icon name={r.icon} size={15} />
              </span>
              <span className="role-list-text">
                <span className="role-list-title">{roleName(r)}</span>
                <span className="mini-tag">{r.type}</span>
              </span>
            </span>
            <span className="mono" style={{ color: r.members ? 'var(--fg-default)' : 'var(--fg-subtle)' }}>{r.members}</span>
            <span className="mono" style={{ color: 'var(--fg-muted)', fontSize: 11 }}>{r.envSummary}</span>
            <span className="access-level">{r.level}</span>
            <span onClick={e => e.stopPropagation()}>
              <button className="icon-btn ghost sm"><Icon name="ellipsis" size={14} /></button>
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

/* =========================================================================
   ROLE — detail
   ========================================================================= */
function CapVal({ state }) {
  const s = CAP_STATE[state] || CAP_STATE.none;
  return (
    <span className={`cap-val ${s.cls}`}>
      {s.icon && <Icon name={s.icon} size={12} />}
      {s.label}
    </span>
  );
}

function RoleDetail({ role, onClose }) {
  if (!role) return null;
  const envs = role.env || ROLE_ENV[role.id] || [];
  const people = (typeof MEMBERS !== 'undefined' ? MEMBERS : []).filter(m => m.role === role.id);

  return (
    <div className="detail">
      <div className="detail-head">
        <div className="detail-id">
          <span className={`role-ic lg ${role.id === 'owner' ? 'owner' : ''} ${role.type === 'custom' ? 'custom' : ''}`}>
            <Icon name={role.icon} size={20} />
          </span>
          <div className="member-text">
            <span className="detail-eyebrow">{role.type} role</span>
            <span className="detail-title">{roleName(role)}</span>
            <span className="detail-sub mono">{role.members} member{role.members === 1 ? '' : 's'}</span>
          </div>
        </div>
        <div className="detail-head-actions">
          <Btn variant="ghost" size="sm" icon={role.type === 'system' ? 'copy' : 'pencil'}>
            {role.type === 'system' ? 'Duplicate' : 'Edit'}
          </Btn>
          <button className="icon-btn ghost sm"><Icon name="ellipsis" size={14} /></button>
          <button className="icon-btn ghost sm" onClick={onClose}><Icon name="x" size={14} /></button>
        </div>
      </div>

      <div className="detail-body">
        <div className="dbody">
          <p className="role-detail-desc">{roleDesc(role)}</p>

          <div className="dsection">
            <span className="eyebrow">Environment access</span>
            <div className="acc-list">
              {envs.map(([env, perm]) => (
                <div className="acc-row" key={env}>
                  <span className="acc-env">
                    <Icon name={env === 'production' ? 'globe' : 'layers'} size={14} />{env}
                  </span>
                  <span className={`acc-perm ${perm}`}>{PERM_TXT[perm]}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="dsection">
            <span className="eyebrow">Permissions</span>
            <div className="caps">
              {CAP_GROUPS.map(g => (
                <div className="cap-group" key={g.group}>
                  <div className="cap-group-label">{g.group}</div>
                  {g.rows.map(row => (
                    <div className="cap-row" key={row.label}>
                      <span className="cap-name">{row.label}</span>
                      <CapVal state={role.caps ? (role.caps[row.label] || 'none') : row.vals[role.id]} />
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </div>

          <div className="dsection">
            <div className="dsection-head">
              <span className="eyebrow">Members</span>
              <span className="toolbar-meta mono">{people.length}</span>
            </div>
            {people.length > 0 ? (
              <div className="role-members">
                {people.map(m => (
                  <div className="rm-row" key={m.id}>
                    <span className={`uavatar ${m.role === 'owner' ? 'is-owner' : ''}`}>{m.initials}</span>
                    <span className="member-text">
                      <span className="member-name">{m.name}</span>
                      <span className="member-email mono">{m.email}</span>
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <div className="role-empty">No members assigned yet.</div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { RolesPage, RoleDetail, ROLES, ROLE_ENV, CAP_GROUPS, PERM_TXT, CAP_STATE, roleName, roleDesc });

// frontend/src/app/components/roles/roles.component.ts
import { Component, HostListener, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IconComponent } from '../shared/icon/icon.component';
import { AuthService } from '../../auth/auth.service';
import { AdminService } from '../../services/admin.service';
import { NotificationService } from '../../services/notification.service';
import { Role, RoleDetail, CapabilityCatalogue, AuthUser } from '../../auth/auth.models';
import { capMeta, initials, CapStateMeta } from '../users/admin.data';

type RoleFilter = 'all' | 'system' | 'custom';

/**
 * Admin · Roles — real-data implementation of the role-management design. Lists
 * the role catalogue from /api/v1/roles, shows a role-detail panel (capability
 * matrix + assigned members) and the create-custom-role modal. Environment
 * access is intentionally omitted until environments exist.
 */
@Component({
  selector: 'app-roles',
  standalone: true,
  imports: [CommonModule, FormsModule, IconComponent],
  styleUrls: ['./roles.component.scss'],
  templateUrl: './roles.component.html',
})
export class RolesComponent implements OnInit {
  readonly initials = initials;
  readonly capMeta = capMeta;

  readonly roleCols = 'minmax(0,1.7fr) 90px minmax(0,1fr) 30px';
  readonly filters: { id: RoleFilter; label: string }[] = [
    { id: 'all',    label: 'All' },
    { id: 'system', label: 'System' },
    { id: 'custom', label: 'Custom' },
  ];
  readonly CR_ICONS = ['shield-check', 'siren', 'wrench', 'rocket', 'terminal', 'bell-ring', 'eye', 'key-round'];

  loading = signal(true);
  roles = signal<Role[]>([]);
  catalogue = signal<CapabilityCatalogue | null>(null);

  selectedId: string | null = null;
  detail = signal<RoleDetail | null>(null);
  detailLoading = signal(false);
  filter: RoleFilter = 'all';

  // create modal
  creating = false;
  saving = false;
  crName = '';
  crDesc = '';
  crIcon = 'shield-check';
  crBase = 'none';
  crCaps: Record<string, string> = {};

  constructor(
    public auth: AuthService,
    private admin: AdminService,
    private notify: NotificationService,
  ) {}

  ngOnInit(): void {
    if (this.auth.isAdmin()) this.load();
    else this.loading.set(false);
  }

  load(): void {
    this.loading.set(true);
    this.admin.getCapabilities().subscribe({ next: c => this.catalogue.set(c), error: () => {} });
    this.admin.listRoles().subscribe({
      next: r => {
        this.roles.set(r);
        if (this.selectedId == null && r.length) this.select(r[0].id);
        else if (this.selectedId) this.loadDetail(this.selectedId);
        this.loading.set(false);
      },
      error: () => this.loading.set(false),
    });
  }

  // ---- list ----
  get filtered(): Role[] {
    return this.roles().filter(r => this.filter === 'all' || r.type === this.filter);
  }
  get counts(): Record<RoleFilter, number> {
    const rs = this.roles();
    return {
      all: rs.length,
      system: rs.filter(r => r.type === 'system').length,
      custom: rs.filter(r => r.type === 'custom').length,
    };
  }

  select(id: string): void {
    this.selectedId = id;
    this.loadDetail(id);
  }
  loadDetail(id: string): void {
    this.detailLoading.set(true);
    this.detail.set(null);
    this.admin.getRole(id).subscribe({
      next: d => { this.detail.set(d); this.detailLoading.set(false); },
      error: () => this.detailLoading.set(false),
    });
  }
  closeDetail(): void { this.selectedId = null; this.detail.set(null); }

  // ---- detail helpers ----
  capState(role: RoleDetail | null, key: string): CapStateMeta {
    return capMeta(role?.capabilities?.[key]);
  }
  members(role: RoleDetail | null): AuthUser[] { return role?.member_list || []; }

  // ---- create modal ----
  private blankCaps(): Record<string, string> {
    const out: Record<string, string> = {};
    for (const g of this.catalogue()?.groups || []) {
      for (const row of g.rows) out[row.key] = 'none';
    }
    return out;
  }
  openCreate(): void {
    this.crName = '';
    this.crDesc = '';
    this.crIcon = 'shield-check';
    this.crBase = 'none';
    this.crCaps = this.blankCaps();
    this.creating = true;
  }
  closeCreate(): void { if (!this.saving) this.creating = false; }

  pickBase(id: string): void {
    this.crBase = id;
    if (id === 'none') { this.crCaps = this.blankCaps(); return; }
    const base = this.roles().find(r => r.id === id);
    this.crCaps = base ? { ...this.blankCaps(), ...base.capabilities } : this.blankCaps();
  }

  setCap(key: string, value: string): void { this.crCaps = { ...this.crCaps, [key]: value }; }

  /** System roles offered as "start from" templates. */
  get templates(): Role[] { return this.roles().filter(r => r.type === 'system' && r.id !== 'owner'); }

  get crValid(): boolean { return this.crName.trim().length > 0; }

  createRole(): void {
    if (!this.crValid || this.saving) return;
    this.saving = true;
    this.admin.createRole({
      name: this.crName.trim(),
      description: this.crDesc.trim(),
      icon: this.crIcon,
      capabilities: this.crCaps,
    }).subscribe({
      next: role => {
        this.saving = false;
        this.creating = false;
        this.filter = 'all';
        this.notify.success(`Created role “${role.name}”`);
        this.selectedId = role.id;
        this.load();
      },
      error: e => { this.saving = false; this.notify.error(e?.error?.error || 'Failed to create role'); },
    });
  }

  @HostListener('document:keydown.escape')
  onEscape(): void { if (this.creating) this.closeCreate(); }
}

@if (!auth.isAdmin()) {
  <div class="content-area">
    <div class="empty-state" style="margin:auto;text-align:center;color:var(--fg-subtle);padding:64px;">
      <dy-icon name="lock" [size]="22"></dy-icon>
      <p>Role management is available to admins only.</p>
    </div>
  </div>
} @else {
<div class="body" [class.no-detail]="!selectedId">

  <!-- ════════════════════ LEFT · Roles table ════════════════════ -->
  <div class="content-area">
    <div class="content-head">
      <div class="content-title-row">
        <h2 class="content-title">Roles</h2>
        <span class="content-count mono">{{ filtered.length }} of {{ roles().length }}</span>
      </div>
      <div class="content-actions">
        <button class="btn btn-ghost" (click)="load()"><dy-icon name="refresh-cw" [size]="14"></dy-icon> Refresh</button>
        <span class="divider-v"></span>
        <button class="btn btn-primary" (click)="openCreate()"><dy-icon name="plus" [size]="14"></dy-icon> New role</button>
      </div>
    </div>

    <div class="content-toolbar">
      <div class="pills">
        @for (f of filters; track f.id) {
          <button class="pill" [class.on]="filter === f.id" (click)="filter = f.id">
            {{ f.label }}<span class="pill-count">{{ counts[f.id] }}</span>
          </button>
        }
      </div>
      <div class="toolbar-meta mono">{{ counts.system }} system · {{ counts.custom }} custom</div>
    </div>

    @if (loading()) {
      <div class="empty-state" style="padding:48px;text-align:center;color:var(--fg-subtle);">Loading roles…</div>
    } @else {
      <div class="gtable roles-table">
        <div class="gtable-head" [style.grid-template-columns]="roleCols">
          <span>Role</span>
          <span>Users</span>
          <span>Access level</span>
          <span></span>
        </div>
        @for (r of filtered; track r.id) {
          <div class="gtable-row roles-row" [class.sel]="selectedId === r.id"
               [style.grid-template-columns]="roleCols" (click)="select(r.id)">
            <span class="role-list-name">
              <span class="role-ic" [class.owner]="r.id === 'owner'" [class.custom]="r.type === 'custom'">
                <dy-icon [name]="r.icon" [size]="15"></dy-icon>
              </span>
              <span class="role-list-text">
                <span class="role-list-title">{{ r.name }}</span>
                <span class="mini-tag">{{ r.type }}</span>
              </span>
            </span>
            <span class="mono" [style.color]="r.members ? 'var(--fg-default)' : 'var(--fg-subtle)'">{{ r.members }}</span>
            <span class="access-level">{{ r.level }}</span>
            <span></span>
          </div>
        }
      </div>
    }
  </div>

  <!-- ════════════════════ RIGHT · Role detail ════════════════════ -->
  @if (selectedId) {
    <div class="detail admin-detail">
      @if (detail(); as role) {
        <div class="detail-head">
          <div class="detail-id">
            <span class="role-ic lg" [class.owner]="role.id === 'owner'" [class.custom]="role.type === 'custom'">
              <dy-icon [name]="role.icon" [size]="20"></dy-icon>
            </span>
            <div class="member-text">
              <span class="detail-eyebrow">{{ role.type }} role</span>
              <span class="detail-title">{{ role.name }}</span>
              <span class="detail-sub mono">{{ role.members }} user{{ role.members === 1 ? '' : 's' }}</span>
            </div>
          </div>
          <div class="detail-head-actions">
            <button class="icon-btn ghost sm" (click)="closeDetail()"><dy-icon name="x" [size]="14"></dy-icon></button>
          </div>
        </div>

        <div class="detail-body">
          <div class="dbody">
            <p class="role-detail-desc">{{ role.description }}</p>

            <div class="dsection">
              <span class="eyebrow">Permissions</span>
              <div class="caps">
                @for (g of catalogue()?.groups || []; track g.group) {
                  <div class="cap-group">
                    <div class="cap-group-label">{{ g.group }}</div>
                    @for (row of g.rows; track row.key) {
                      <div class="cap-row">
                        <span class="cap-name">{{ row.label }}</span>
                        <span class="cap-val {{ capState(role, row.key).cls }}">
                          @if (capState(role, row.key).icon) { <dy-icon [name]="capState(role, row.key).icon!" [size]="12"></dy-icon> }
                          {{ capState(role, row.key).label }}
                        </span>
                      </div>
                    }
                  </div>
                }
              </div>
            </div>

            <div class="dsection">
              <div class="dsection-head">
                <span class="eyebrow">Users</span>
                <span class="toolbar-meta mono">{{ members(role).length }}</span>
              </div>
              @if (members(role).length > 0) {
                <div class="role-members">
                  @for (m of members(role); track m.id) {
                    <div class="rm-row">
                      <span class="uavatar" [class.is-owner]="m.role === 'owner'">{{ initials(m) }}</span>
                      <span class="member-text">
                        <span class="member-name">{{ m.full_name || m.username }}</span>
                        <span class="member-email mono">{{ m.email || '@' + m.username }}</span>
                      </span>
                    </div>
                  }
                </div>
              } @else {
                <div class="role-empty">No users assigned yet.</div>
              }
            </div>
          </div>
        </div>
      } @else {
        <div class="empty-state" style="padding:48px;text-align:center;color:var(--fg-subtle);">Loading role…</div>
      }
    </div>
  }
</div>

<!-- ════════════════════ Create role · modal ════════════════════ -->
@if (creating) {
  <div class="amodal-backdrop" (mousedown)="closeCreate()">
    <div class="amodal amodal-lg" (mousedown)="$event.stopPropagation()">
      <div class="amodal-head">
        <span class="role-ic custom"><dy-icon [name]="crIcon" [size]="16"></dy-icon></span>
        <div class="amodal-title-wrap">
          <span class="amodal-eyebrow">New role</span>
          <div class="amodal-title">{{ crName.trim() || 'Untitled role' }}</div>
          <div class="amodal-sub mono">custom role</div>
        </div>
        <button class="icon-btn ghost sm" (click)="closeCreate()"><dy-icon name="x" [size]="14"></dy-icon></button>
      </div>

      <div class="amodal-body">
        <!-- DETAILS -->
        <div class="form-section">
          <div class="field">
            <span class="form-label">Role name</span>
            <input class="text-input" placeholder="e.g. On-call SRE" [(ngModel)]="crName" />
          </div>
          <div class="field">
            <span class="form-label">Description</span>
            <textarea class="text-input" placeholder="What can people with this role do?" [(ngModel)]="crDesc" rows="2"></textarea>
          </div>
          <div class="field">
            <span class="form-label">Icon</span>
            <div class="icon-pick">
              @for (ic of CR_ICONS; track ic) {
                <button type="button" class="icon-opt" [class.on]="crIcon === ic" (click)="crIcon = ic">
                  <dy-icon [name]="ic" [size]="16"></dy-icon>
                </button>
              }
            </div>
          </div>
        </div>

        <!-- TEMPLATE -->
        <div class="form-section">
          <span class="form-label">Start from</span>
          <div class="tmpl-row">
            <button type="button" class="tmpl-chip" [class.on]="crBase === 'none'" (click)="pickBase('none')">
              <dy-icon name="circle-dashed" [size]="13"></dy-icon>Blank
            </button>
            @for (t of templates; track t.id) {
              <button type="button" class="tmpl-chip" [class.on]="crBase === t.id" (click)="pickBase(t.id)">
                <dy-icon [name]="t.icon" [size]="13"></dy-icon>{{ t.name }}
              </button>
            }
          </div>
        </div>

        <!-- PERMISSIONS -->
        <div class="form-section">
          <span class="form-label">Permissions</span>
          <div class="caps">
            @for (g of catalogue()?.groups || []; track g.group) {
              <div class="cap-group">
                <div class="cap-group-label">{{ g.group }}</div>
                @for (row of g.rows; track row.key) {
                  <div class="cap-edit-row">
                    <span class="cap-edit-name">{{ row.label }}</span>
                    <div class="seg seg-perm">
                      @for (st of catalogue()?.states || []; track st.value) {
                        <button type="button" class="seg-opt" [class.on]="crCaps[row.key] === st.value" [class.accent]="crCaps[row.key] === st.value && st.value === 'all'" (click)="setCap(row.key, st.value)">{{ st.label }}</button>
                      }
                    </div>
                  </div>
                }
              </div>
            }
          </div>
        </div>
      </div>

      <div class="amodal-foot">
        <span class="foot-hint mono">creates a custom role · 0 users</span>
        <div class="foot-right">
          <button class="btn btn-ghost" (click)="closeCreate()">Cancel</button>
          <button class="btn btn-primary" [class.is-disabled]="!crValid || saving" (click)="createRole()"><dy-icon name="check" [size]="14"></dy-icon> {{ saving ? 'Creating…' : 'Create role' }}</button>
        </div>
      </div>
    </div>
  </div>
}
}
